name              'build-essential'
maintainer        'Chef Software, Inc.'
maintainer_email  'cookbooks@chef.io'
license           'Apache 2.0'
description       'LS Forks of public cookbook Installs C compiler / build tools'
long_description IO.read(File.join(File.dirname(__FILE__), 'README.md'))
version           '3.2.1'
recipe            'build-essential', 'Installs packages required for compiling C software from source.'
chef_version      '~> 12.12'

supports 'amazon'
supports 'centos'
supports 'debian'
supports 'fedora'
supports 'freebsd'
supports 'mac_os_x', '>= 10.7.0'
supports 'mac_os_x_server', '>= 10.7.0'
supports 'oracle'
supports 'redhat'
supports 'scientific'
supports 'smartos'
supports 'suse'
supports 'ubuntu'
supports 'windows'

depends 'seven_zip'

source_url       'https://github.com/lightspeedretail/chef-build-essential'
issues_url       'https://jira.atlightspeed.net/projects/HSRE'